### PR TITLE
Streaming Filter Support

### LINKED ISSUE #1025: Filter Support Redux
So we currently have #854 in-flight which was paused due to the work upstream in https://github.com/libgit2/libgit2/pull/2911 to add in streaming filter support.

I've grabbed this PR, rebased it on top of vNext and am working through the necessary changes. Once I'm happy with the passing tests, I'll grab some of @ammeep's time to get a :thumbsup: and she can finish up this PR.

Anyway, a couple of questions while I'm working through tests:

- the proxy method for `git_buf_put` doesn't exist - should I submit a PR for this patch https://github.com/libgit2/libgit2/commit/a2012c4?
- I'm seeing a bunch of  `LibGit2Sharp.EntryExistsException : A filter with the name 'cipher-filter' is already registered` in tests - not sure what's changed - thoughts? 

cc @ethomson

### PR DESCRIPTION
**Pull request by whoisj**
Completes the work started by @ammeep for getting filters working in Libgit2Sharp (thanks for the awesome starting point!). Makes use of the streaming filter infrastructure added by @ethomson in Libgit2 to minimize the memory footprint. The goal is to support the Git-LFS filter, so one has to assume the streams won't fit in memory.

Fairly simple design. Added a new `GitWriteStream` to wrap the native `git_writestream`, then implements all logic for doing the actual stream work in the `Filter` base class. The rest of the work was done by @ammeep :cool: 

Fixes #1025

### CODE REVIEW

File: LibGit2Sharp/Core/GitWriteStream.cs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+        [MarshalAs(UnmanagedType.FunctionPtr)]
+        public write_fn write;
+
+        [MarshalAs(UnmanagedType.FunctionPtr)]
+        public close_fn close;
+
+        [MarshalAs(UnmanagedType.FunctionPtr)]
+        public free_fn free;        
+
+        public delegate int write_fn(IntPtr stream, IntPtr buffer, uint len);
```
Comment (nulltoken) [inline LibGit2Sharp/Core/GitWriteStream.cs]: I think we should rather marshal `size_t` into a `UIntPtr`

File: LibGit2Sharp/Core/NativeMethods.cs [hunk 2]
```diff
@@ -192,6 +192,12 @@ static NativeMethods()
             [MarshalAs(UnmanagedType.CustomMarshaler, MarshalCookie = UniqueId.UniqueIdentifier, MarshalTypeRef = typeof(StrictUtf8Marshaler))] string canonical_branch_name);
 
         [DllImport(libgit2)]
+        internal static extern int git_buf_grow(IntPtr buffer, UIntPtr targetSize);
+
+        [DllImport(libgit2)]
+        internal static extern int git_buf_put(IntPtr buffer, IntPtr data, UIntPtr len);
```
Comment (nulltoken) [inline LibGit2Sharp/Core/NativeMethods.cs]: This is no longer needed. Could you please remove this from Amy's commit?

File: LibGit2Sharp/Core/Proxy.cs [hunk 3]
```diff
@@ -241,6 +241,33 @@ public static string git_branch_upstream_name(RepositorySafeHandle handle, strin
...
+        public static void git_buf_grow(IntPtr gitBufPointer, ulong target_size)
+        {
+            using (ThreadAffinity())
+            {
+                var res = NativeMethods.git_buf_grow(gitBufPointer, (UIntPtr)target_size);
+                Ensure.ZeroResult(res);
+            }
+        }
+
+        public static void git_buf_put(IntPtr gitBufPointer, byte[] data, int offset, int count)
```
Comment (nulltoken) [inline LibGit2Sharp/Core/Proxy.cs]: This is no longer needed. Could you please remove this from Amy's commit?

File: LibGit2Sharp/Filter.cs [hunk 4]
```diff
@@ -0,0 +1,300 @@
...
+            nextStream = new GitWriteStream();
+            Marshal.PtrToStructure(nextPtr, nextStream);
+            filterSource = FilterSource.FromNativePtr(filterSourcePtr);
+
+            git_writestream_out = thisPtr;
+
+            return 0;
+        }
+
+        unsafe int StreamCloseCallback(IntPtr stream)
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: Unneeded `unsafe` modifier here. Could you please drop it?

File: LibGit2Sharp/Filter.cs [hunk 5]
```diff
@@ -0,0 +1,300 @@
...
+            }
+            if (stream != thisPtr)
+            {
+                throw new ArgumentException("unexpected stream ptr");
+            }
+
+            return nextStream.close(nextPtr);
+        }
+
+        unsafe void StreamFreeCallback(IntPtr stream)
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: Here as well

File: LibGit2Sharp/Filter.cs [hunk 6]
```diff
@@ -0,0 +1,300 @@
...
+        /// If non-NULL, the filter's `initialize` callback will be invoked right
+        /// before the first use of the filter, so you can defer expensive
+        /// initialization operations (in case libgit2 is being used in a way that doesn't need the filter).
+        /// </summary>
+        int InitializeCallback(IntPtr filterPointer)
+        {
+            return Initialize();
+        }
+
+        unsafe int StreamCallback(out IntPtr git_writestream_out, GitFilter self, IntPtr payload, IntPtr filterSourcePtr, IntPtr git_writestream_next)
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: here as well

File: LibGit2Sharp/Filter.cs [hunk 7]
```diff
@@ -0,0 +1,300 @@
...
+                else if (result < 0)
+                {
+                    return result;
+                }
+
+                byte[] bytes = new byte[32 * 1024];
+                IntPtr bytesPtr = Marshal.AllocHGlobal(bytes.Length);
+                try
+                {
+                    long length = output.Position;
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: This variable doesn't look like to be used.

File: LibGit2Sharp/Filter.cs [hunk 8]
```diff
@@ -0,0 +1,300 @@
...
+            using (UnmanagedMemoryStream input = new UnmanagedMemoryStream((byte*)buffer.ToPointer(), len))
+            using (MemoryStream output = new MemoryStream())
+            {
+                switch (filterSource.SourceMode)
+                {
+                    case FilterMode.Clean:
+                        result = Clean(filterSource.Path, input as Stream, output as Stream);
+                        break;
+                    case FilterMode.Smudge:
+                        result = Smudge(filterSource.Path, input as Stream, output as Stream);
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: I think the `as Stream` cast are useless here and above.

File: LibGit2Sharp/Filter.cs [hunk 9]
```diff
@@ -0,0 +1,300 @@
...
+            return Initialize();
+        }
+
+        unsafe int StreamCallback(out IntPtr git_writestream_out, GitFilter self, IntPtr payload, IntPtr filterSourcePtr, IntPtr git_writestream_next)
+        {
+            if (filterSourcePtr == IntPtr.Zero)
+            {
+                throw new ArgumentNullException("filterSourcePtr");
+            }
+            if(git_writestream_next == IntPtr.Zero)
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: Maybe a newline before this statement? (and below as well, please)

File: LibGit2Sharp/Filter.cs [hunk 10]
```diff
@@ -0,0 +1,300 @@
...
+                throw new ArgumentException("unexpected stream ptr");
+            }
+
+            return nextStream.close(nextPtr);
+        }
+
+        unsafe void StreamFreeCallback(IntPtr stream)
+        {
+            if (stream == IntPtr.Zero)
+                throw new ArgumentNullException("stream");
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: Could you please wrap this in braces?

File: LibGit2Sharp/Filter.cs [hunk 11]
```diff
@@ -0,0 +1,300 @@
...
+            if (stream != thisPtr)
+                throw new ArgumentException("unexpected stream ptr");
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: Braces here as well, please.

**Comment by nulltoken** [comment]
Wow! That's a pretty nice interop job. Thanks for giving some love to those filters.

/cc @shiftkey @ammeep @ethomson @jamill @Therzok Could you please also take a peek at this PR?

**Comment by ethomson** [comment]
I think this looks great.  Thanks @whoisj

File: LibGit2Sharp/FilterAttributeEntry.cs [hunk 12]
```diff
@@ -0,0 +1,47 @@
...
+
+        /// <summary>
+        /// The name of the filter found in a .gitattributes file
+        /// </summary>
+        /// <param name="filterName">The name of the filter</param>
+        public FilterAttributeEntry(string filterName)
+        {
+            Ensure.ArgumentNotNullOrEmptyString(filterName, "filterName");
+
+            if (!filterName.Contains(AttributeFilterDefinition))
```
Comment (jamill) [inline LibGit2Sharp/FilterAttributeEntry.cs]: Is `Contains(...)` the right check here? I was kinda expecting a `StartsWith(...)` with an explicit string comparer...

File: LibGit2Sharp/Filter.cs [hunk 13]
```diff
@@ -0,0 +1,300 @@
...
+
+            Marshal.FreeHGlobal(thisPtr);
+        }
+
+        unsafe int StreamWriteCallback(IntPtr stream, IntPtr buffer, uint len)
+        {
+            int result = 0;
+
+            if (stream == IntPtr.Zero)
```
Comment (ethomson) [inline LibGit2Sharp/Filter.cs]: We might could have an `Ensure.NotNullIntPtr` or something similar helper here.

File: LibGit2Sharp/Core/Proxy.cs [hunk 14]
```diff
@@ -821,6 +848,47 @@ public static GitDiffDelta git_diff_get_delta(DiffSafeHandle diff, int idx)
...
+        {
+            var res = NativeMethods.git_filter_source_mode(filterSource);
+            return (FilterMode)res;
+        }
+
+        public static void git_filter_free(IntPtr gitFilter)
+        {
+            using (ThreadAffinity())
+            {
+                NativeMethods.git_filter_free(gitFilter);
```
Comment (ethomson) [inline LibGit2Sharp/Core/Proxy.cs]: We don't need the `using ThreadAffinity` here since there's no error code returned.

File: LibGit2Sharp/Core/Proxy.cs [hunk 15]
```diff
@@ -241,6 +241,33 @@ public static string git_branch_upstream_name(RepositorySafeHandle handle, strin
 
         #region git_buf_
 
+        public static void git_buf_grow(IntPtr gitBufPointer, ulong target_size)
```
Comment (ethomson) [inline LibGit2Sharp/Core/Proxy.cs]: Similarly, let's not bind `git_buf_grow` unless we need to.

File: LibGit2Sharp/Core/NativeMethods.cs [hunk 16]
```diff
@@ -192,6 +192,12 @@ static NativeMethods()
             [MarshalAs(UnmanagedType.CustomMarshaler, MarshalCookie = UniqueId.UniqueIdentifier, MarshalTypeRef = typeof(StrictUtf8Marshaler))] string canonical_branch_name);
 
         [DllImport(libgit2)]
+        internal static extern int git_buf_grow(IntPtr buffer, UIntPtr targetSize);
```
Comment (ethomson) [inline LibGit2Sharp/Core/NativeMethods.cs]: Also hopefully this is no longer necessary.

File: LibGit2Sharp/FilterAttributeEntry.cs [hunk 17]
```diff
@@ -0,0 +1,47 @@
...
+    /// <summary>
+    /// The definition for a given filter found in the .gitattributes file.
+    /// The filter definition will result as 'filter=filterName'
+    ///
+    /// In the .gitattributes file a filter will be matched to a pathspec like so
+    /// '*.txt filter=filterName'
+    /// </summary>
+    public class FilterAttributeEntry
+    {
+        private const string AttributeFilterDefinition = "filter=";
```
Comment (jamill) [inline LibGit2Sharp/FilterAttributeEntry.cs]: Why we need to prefix our filter names with "filter=". If this a requirement of the lg2 API, then could it just take the name of the filter? It seems cleaner to just register the name of the "filter", without having to prefix it with this magic string.

/cc @ethomson

File: LibGit2Sharp/FilterMode.cs [hunk 18]
```diff
@@ -0,0 +1,20 @@
...
+        /// </summary>
+        Smudge = 0,
+
+        /// <summary>
+        /// Clean occurs when importing a file from the working directory to the Git object database.
+        /// For example, a file would be cleaned when staging a file.
+        /// </summary>
+        Clean = (1 << 0),
+    }
+}
```
Comment (jamill) [inline LibGit2Sharp/FilterMode.cs]: nit: trailing newline

File: LibGit2Sharp/Filter.cs [hunk 19]
```diff
@@ -0,0 +1,300 @@
...
+                try
+                {
+                    long length = output.Position;
+                    output.Seek(0, SeekOrigin.Begin);
+
+                    int read = 0;
+                    while ((read = output.Read(bytes, 0, bytes.Length)) > 0)
+                    {
+                        Marshal.Copy(bytes, 0, bytesPtr, read);
+                        if ((result = nextStream.write(nextPtr, bytesPtr, (uint)read)) < 0)
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: This might already be covered by @nulltoken  - but this is another place we are missing enclosing braces

File: LibGit2Sharp/FilterAttributeEntry.cs (hunk 17 above)
Comment (ethomson) [inline LibGit2Sharp/FilterAttributeEntry.cs]: Right, so: the libgit2 API here allows for some real deep configuration, and we are happy to match on either a simple `name` or a `name=value` pair.  This is because we implement `crlf` and `ident` attributes as filters...  so you can register a filter that will be called when a bare word is seen in a `.gitattributes` file (like `crlf`) instead of making one specify `filter=crlf`.

That said, I personally think that this level of detail is not something that we need to expose for LibGit2Sharp.

File: LibGit2Sharp/Filter.cs [hunk 20]
```diff
@@ -0,0 +1,300 @@
...
+            return 0;
+        }
+
+        /// <summary>
+        /// Clean the input stream and write to the output stream.
+        /// </summary>
+        /// <param name="path">The path of the file being filtered</param>
+        /// <param name="input">The git buf input reader</param>
+        /// <param name="output">The git buf output writer</param>
+        /// <returns>0 if successful and <see cref="GitErrorCode.PassThrough"/> to skip and pass through</returns>
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: Are `0` and `GitErrorCode.PassThrough` the only values that this method should return? Can it return other values to represent other error codes? Other delagates in lg2# that support cancellation have a `bool` return type.

File: LibGit2Sharp/FilterAttributeEntry.cs (hunk 17 above)
Comment (jamill) [inline LibGit2Sharp/FilterAttributeEntry.cs]: So, if I understand your proposal- you are suggesting that LG2# always takes just the name of the filter, and will always prepend it with `filter=` (i.e. skip the `Contains(...)` check)? I like the consistency of that approach.

Comment (ethomson) [inline LibGit2Sharp/FilterAttributeEntry.cs]: Yes; thanks for turning my vague ramblings into something coherent.  That's what I'm thinking.  Drop support entirely for registering filters that aren't prefixed by `filter=` at all in LibGit2Sharp.

If we *really* want to support matching these types of filters, then have a `SomethingElseAttributeEntry` for them and not expose this `filter=` to the end-users.  But I think we can add that later, if it's ever needed, which I don't think it will be.

Comment (nulltoken) [inline LibGit2Sharp/FilterAttributeEntry.cs]: :+1:

File: LibGit2Sharp/Filter.cs (hunk 9 above)
Comment (whoisj) [inline LibGit2Sharp/Filter.cs]: I'm sorry to be dense, but I don't understand the comment? A new line before and after the comment, the method signature, or something else?

**Comment by shiftkey** [comment]
:eyes: will test this out against GHfW

File: LibGit2Sharp/FilterAttributeEntry.cs (hunk 12 above)
Comment (whoisj) [inline LibGit2Sharp/FilterAttributeEntry.cs]: Agreed, I'll change this to be `.StartsWith(..., Ordinal)`

File: LibGit2Sharp/Core/Proxy.cs (hunk 15 above)
Comment (whoisj) [inline LibGit2Sharp/Core/Proxy.cs]: @ethomson removed as part of @nulltoken request about not adding unused native bindings.

File: LibGit2Sharp/Filter.cs (hunk 13 above)
Comment (whoisj) [inline LibGit2Sharp/Filter.cs]: Agreed. I'll add a pair of new Ensure methods. One for not null and one for expected value (these seem to be the reasonable, constant cases).

**Comment by whoisj** [comment]
@jamill Yes, agreed - literals (aka magic numbers) should be moved into constants. My bad, tired brains take shortcuts. I'll fix this up ASAP. As for the exception, I'm using it as flow control. I suppose I should use something cheaper like a `continue` or `goto` and keep the exception for exceptional circumstances. 

In general, is it better in a native-managed-native call stack to just avoid exceptions all together? Every project seems to have its own set of rules about this. I don't see anything in the .md files about this. What is expected in Libgit2Sharp?

/cc @nulltoken , @ethomson , @shiftkey

**Comment by whoisj** [comment]
Thanks for all of the great feedback. Fixes pushed for all with the exception of the discussion @ethomson and @jamill are having with regards to requiring "filter=".

**Comment by jamill** [comment]
>  @ethomson and @jamill having with regards to requiring "filter=". I'm not sure if that should be part of this PR or not.

I think @ethomson and I are in agreement on always adding the `filter=` prefix to the filter name, and expect that clients will never specify the `filter=` prefix. I would prefer to have this behavior in the original version, if it is not too much work (unless @ammeep or others have objections), but not too strongly. I could see this going in in a separate PR.

File: LibGit2Sharp/Filter.cs (hunk 9 above)
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: My fault. I was unclear. I was pondering, for readability purpose, if we shouldn't add a newline between the closing brace and the `if`.

In other words, turn the following

```
if (filterSourcePtr == IntPtr.Zero)
{
     throw new ArgumentNullException("filterSourcePtr");
}
if(git_writestream_next == IntPtr.Zero)
{
 ....
```

into

```
if (filterSourcePtr == IntPtr.Zero)
{
     throw new ArgumentNullException("filterSourcePtr");
}

if(git_writestream_next == IntPtr.Zero)
{
 ....
```

Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: While you're at it, could you please also add a space between `if`s and opening parentheses? (ie. `if(git_write....)` -> `if (git_write...)`

**Comment by ammeep** [comment]
@whoisj this is wonderful! Thank you so much for taking this on, I have been swamped. :heart_eyes: 

We ended up making a fork of libgit2sharp without the api changes in libgit2, which GitHub for Windows is currently using. https://github.com/github/libgit2sharp/tree/ghfw-p-flow-plus-filters

It includes one change that didn't make it into the original libgit2sharp PR https://github.com/github/libgit2sharp/commit/dbea75ec5f0c0c37b5eed3f888cae8e70fa32d63 which allows us to pass the working directory of the repository to the clean and smudge overloads on the filter. This turns out to be important because most filter CLI tools (or at least the Git LFS CLI) require the working directory of the repository. 

Do you have any objections to adding this to the API contract?

**Comment by whoisj** [comment]
@ameep I think that makes sense, no objections here.

**Comment by whoisj** [comment]
Updated the PR with changes requested by @ammeep as well as added a necessary, missing callback on filter close to allow the filter to do any final, necessary work before being closed.

File: LibGit2Sharp/FilterAttributeEntry.cs (hunk 17 above)
Comment (whoisj) [inline LibGit2Sharp/FilterAttributeEntry.cs]: Updated the PR per @ethomson and @jamill feedback. Thanks!

Comment (shiftkey) [inline LibGit2Sharp/FilterAttributeEntry.cs]: :thumbsup:

File: LibGit2Sharp/FilterAttributeEntry.cs [hunk 21]
```diff
@@ -0,0 +1,51 @@
...
+        /// <param name="filterName">The name of the filter as found in the .gitattributes file without the "filter=" prefix</param>
+        /// <remarks>
+        /// "filter=" will be prepended to the filterDefinition, therefore the "filter=" portion of the filter
+        /// name shouldbe omitted on declaration. Inclusion of the "filter=" prefix will cause the FilterDefinition to
+        /// fail to match the .gitattributes entry and thefore no be invoked correctly.
+        /// </remarks>
+        public FilterAttributeEntry(string filterName)
+        {
+            Ensure.ArgumentNotNullOrEmptyString(filterName, "filterName");
+            if (filterName.StartsWith("filter=", StringComparison.OrdinalIgnoreCase))
```
Comment (jamill) [inline LibGit2Sharp/FilterAttributeEntry.cs]: Cool - thanks! however, missing enclosing curly braces

**Comment by shiftkey** [comment]
Just ran this through our existing test suite in GitHub for Windows - I'm :thumbsup: on this PR. Thanks for the hard work @whoisj!

File: LibGit2Sharp/Core/Ensure.cs [hunk 22]
```diff
@@ -87,6 +87,33 @@ public static void ArgumentDoesNotContainZeroByte(string argumentValue, string a
...
+            }
+        }
+
+        /// <summary>
+        /// Checks a pointer argument to ensure it is the expected pointer value.
+        /// </summary>
+        /// <param name="argumentValue">The argument value to check.</param>
+        /// <param name="expectedValue">The expected value.</param>
+        /// <param name="argumentName">The name of the argument.</param>
+        public static void ArhumentIsExpectedIntPtr(IntPtr argumentValue, IntPtr expectedValue, string argumentName)
```
Comment (jamill) [inline LibGit2Sharp/Core/Ensure.cs]: small spelling mistake: `Arhument` => `Argument`

File: LibGit2Sharp/FilterMode.cs [hunk 23]
```diff
@@ -0,0 +1,20 @@
...
+        /// Smudge occurs when exporting a file from the Git object database to the working directory.
+        /// For example, a file would be smudged during a checkout operation.
+        /// </summary>
+        Smudge = 0,
+
+        /// <summary>
+        /// Clean occurs when importing a file from the working directory to the Git object database.
+        /// For example, a file would be cleaned when staging a file.
+        /// </summary>
+        Clean = (1 << 0),
```
Comment (jamill) [inline LibGit2Sharp/FilterMode.cs]: This is not a flag attribute - I think this should be `Clean = 1;`. For the current code, they are the same, but something to be careful about.

Comment (whoisj) [inline LibGit2Sharp/FilterMode.cs]: Agreed. Changed it to use the literal values. The real defines for this enum are defined in libgit2's filter.h file.

**Comment by nulltoken** [comment]
Restarted the MAC OS X build

File: LibGit2Sharp/Core/Proxy.cs [hunk 24]
```diff
@@ -816,7 +816,45 @@ public static int git_diff_num_deltas(DiffSafeHandle diff)
...
+
+        #endregion
+
+        #region git_filter_
+
+        public static void git_filter_register(string name, FilterRegistration filterRegistration, int priority)
+        {
+            using (ThreadAffinity())
+            {
+                int res = NativeMethods.git_filter_register(name, filterRegistration.FilterPointer, priority);
```
Comment (jamill) [inline LibGit2Sharp/Core/Proxy.cs]: Just curious - how come libgit2 relies on the caller to allocate and manage the memory for the `git_filter` struct, instead of libgit2 making a copy of the data? I can see precedence both ways (the network subtransport registration relies on the caller to manage the memory, while structs like remote callbacks are copied into memory owned by libgit2). To me, it seems like it would be easier if libgit2 just copied the struct into memory that it owned, and the caller was just responsible for keeping the managed functions around.

/cc @ethomson

File: LibGit2Sharp/Core/NativeMethods.cs [hunk 25]
```diff
@@ -499,6 +498,21 @@ static NativeMethods()
...
+
+        [DllImport(libgit2)]
+        internal static extern int git_filter_unregister(
+            [MarshalAs(UnmanagedType.CustomMarshaler, MarshalCookie = UniqueId.UniqueIdentifier, MarshalTypeRef = typeof(StrictUtf8Marshaler))]string name);
+
+        [DllImport(libgit2)]
+        internal static extern int git_filter_source_mode(IntPtr source);
+
+        [DllImport(libgit2)]
+        internal static extern void git_filter_free(IntPtr filterSafeHandle);
```
Comment (jamill) [inline LibGit2Sharp/Core/NativeMethods.cs]: Is this function exported by libgit2 (still?) I don't see it on the current libgit2 public API.

File: LibGit2Sharp/Filter.cs [hunk 26]
```diff
@@ -0,0 +1,350 @@
...
+                        return result;
+                    }
+
+                    output.Seek(0, SeekOrigin.Begin);
+                    result = WriteToNextFilter(output);
+                }
+            }
+            catch (Exception exception)
+            {
+                Proxy.giterr_set_str(GitErrorCategory.Filter, exception.Message);
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: Might consider using the version of `giterr_set_str(...)` that takes an exception, we recently did some work to format messages from aggregate exceptions or exceptions with inner exceptions (in cases where the important text is not in the top level exception, but buried in an inner exception).

File: LibGit2Sharp/Filter.cs [hunk 27]
```diff
@@ -0,0 +1,350 @@
...
+        void StreamFreeCallback(IntPtr stream)
+        {
+            try
+            {
+                Ensure.ArgumentNotZeroIntPtr(stream, "stream");
+                Ensure.ArgumentIsExpectedIntPtr(stream, thisPtr, "stream");
+
+                Marshal.FreeHGlobal(thisPtr);
+            }
+            catch { }
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: This looks unexpected - do we really want to catch and swallow all exceptions? I would like to at least trace this, but we should decide the correct thing to do here for error handling (if it is just tracing and catching, then maybe document this reason in code).

File: LibGit2Sharp.Tests/FilterFixture.cs [hunk 28]
```diff
@@ -0,0 +1,271 @@
...
+        [Fact]
+        public void CanRegisterAndUnregisterTheSameFilter()
+        {
+            var filter = new EmptyFilter(FilterName + 1, attributes);
+
+            var registration = GlobalSettings.RegisterFilter(filter);
+            GlobalSettings.DeregisterFilter(registration);
+
+            var secondRegistration = GlobalSettings.RegisterFilter(filter);
+            GlobalSettings.DeregisterFilter(secondRegistration);
```
Comment (jamill) [inline LibGit2Sharp.Tests/FilterFixture.cs]: Should we try to put the `DeregisterFilter` call in a try / finally block, to try harder to clean up filter registration if the tests throw an exception? (Not necessarily as part of this PR).

File: LibGit2Sharp/Filter.cs [hunk 29]
```diff
@@ -0,0 +1,350 @@
...
+        }
+
+        /// <summary>
+        /// Clean the input stream and write to the output stream.
+        /// </summary>
+        /// <param name="path">The path of the file being filtered</param>
+        /// <param name="root">The path of the working directory for the owning repository</param>
+        /// <param name="input">Input from the upstream filter or input reader</param>
+        /// <param name="output">Output to the downstream filter or output writer</param>
+        /// <returns>0 if successful and <see cref="GitErrorCode.PassThrough"/> to skip and pass through</returns>
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: `GitErrorCode.PassThrough` is not public - Filter implementors will not have access to this value.

File: LibGit2Sharp/Filter.cs [hunk 30]
```diff
@@ -0,0 +1,350 @@
...
+        {
+            int result = 0;
+
+            try
+            {
+                Ensure.ArgumentNotZeroIntPtr(stream, "stream");
+                Ensure.ArgumentNotZeroIntPtr(buffer, "buffer");
+                Ensure.ArgumentIsExpectedIntPtr(stream, thisPtr, "stream");
+
+                using (UnmanagedMemoryStream input = new UnmanagedMemoryStream((byte*)buffer.ToPointer(), (long)len))
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: We have starting adding helper methods to handle conversion of `UIntPtr` types to `int` or `long`. The particular one to convert `UIntPtr` to `long` is in PR #964 [ConvertToLong](https://github.com/libgit2/libgit2sharp/pull/964/files#diff-1915aa8609ce88f027db96e5b5ca8e70R3736).

Maybe we could just comment to use that method when available? Or maybe no action is required, and we should just audit the code to use this method when available.

File: LibGit2Sharp/Filter.cs [hunk 31]
```diff
@@ -0,0 +1,350 @@
...
+                        default:
+                            Proxy.giterr_set_str(GitErrorCategory.Filter, "Unexpected filter mode.");
+                            return (int)GitErrorCode.Ambiguous;
+                    }
+
+                    if (result == (int)GitErrorCode.PassThrough)
+                    {
+                        input.CopyTo(output);
+                    }
+                    else if (result < 0)
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: How should positive result values be handled?

File: LibGit2Sharp/Filter.cs [hunk 32]
```diff
@@ -0,0 +1,350 @@
...
+                            break;
+                        case FilterMode.Smudge:
+                            result = Smudge(filterSource.Path, filterSource.Root, input, output);
+                            break;
+                        default:
+                            Proxy.giterr_set_str(GitErrorCategory.Filter, "Unexpected filter mode.");
+                            return (int)GitErrorCode.Ambiguous;
+                    }
+
+                    if (result == (int)GitErrorCode.PassThrough)
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: Is it possible that the native layer would handle `PassThrough` for us here? instead of us copying over the bytes?

/cc @ethomson

File: LibGit2Sharp/Filter.cs [hunk 33]
```diff
@@ -0,0 +1,350 @@
...
+            try
+            {
+                Ensure.ArgumentNotZeroIntPtr(stream, "stream");
+                Ensure.ArgumentNotZeroIntPtr(buffer, "buffer");
+                Ensure.ArgumentIsExpectedIntPtr(stream, thisPtr, "stream");
+
+                using (UnmanagedMemoryStream input = new UnmanagedMemoryStream((byte*)buffer.ToPointer(), (long)len))
+                using (MemoryStream output = new MemoryStream())
+                {
+
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: nit: there is an extra empty line after opening brace

**Comment by jamill** [comment]
Thanks @whoisj and @ammeep for this! Awesome work!

File: LibGit2Sharp/Filter.cs (hunk 32 above)
Comment (ethomson) [inline LibGit2Sharp/Filter.cs]: It won't.  That would be a tough API for us to manage in libgit2.  The idea was that if you wanted to pass through that you would simply pass the bytes through unaltered to the next filter yourself...

I think that if you ever decided that you wanted to not apply yourself, that you could just just call the next write callback with your `IntPtr buffer` and `UIntPtr len` and not have to deal with any marshalling.

File: LibGit2Sharp/Core/Proxy.cs (hunk 24 above)
Comment (ethomson) [inline LibGit2Sharp/Core/Proxy.cs]: Because (like the subtransport structure) the idea is that callers have much freedom w/r/t the structure that you are creating.  They need to supply *at minimum* the interface that is defined in the header files so that we can invoke the callbacks and such.  But they may want to provide additional information that is private to themselves.  That is to say, you could:

    struct my_filter {
        struct git_filter base;
        int my_int;
        void *foo;
    }

So you're giving us a struct that covers all our needs, plus you can put whatever you want in it.  We'll give you this pointer back when we ask you to do stuff.  (Taking advantage of this isn't something that we generally do a lot of in LibGit2Sharp, it seems.)

Comment (jamill) [inline LibGit2Sharp/Core/Proxy.cs]: I see - thanks for the explanation (this is also indicated in the documentation for `git_filter`).

File: LibGit2Sharp/Filter.cs (hunk 32 above)
Comment (whoisj) [inline LibGit2Sharp/Filter.cs]: After putting on my C# app developer hat and working with the API directly, I realized this needs some changes. I'm wondering if I should make those changes as part of this PR or create a second PR (in case other disagree with my proposal).

File: LibGit2Sharp/Filter.cs (hunk 31 above)
Comment (whoisj) [inline LibGit2Sharp/Filter.cs]: As I understand it a positive result is undefined. That said, I'm not wholly certain that the Clean and Smudge methods should be returning anything. C# programming model is generally to assume success and traps errors as exceptions. I've got a change locally that does this - debating if I should make that part of this PR or not.

File: LibGit2Sharp/Filter.cs (hunk 29 above)
Comment (whoisj) [inline LibGit2Sharp/Filter.cs]: Yes. Realized this when I started actually developing an actual filter against this API.

This needs to be fixed.

File: LibGit2Sharp.Tests/FilterFixture.cs (hunk 28 above)
Comment (whoisj) [inline LibGit2Sharp.Tests/FilterFixture.cs]: Sounds reasonable.

File: LibGit2Sharp/Filter.cs (hunk 26 above)
Comment (whoisj) [inline LibGit2Sharp/Filter.cs]: Happily. Didn't see that as an option, must have missed it. Thanks.

File: LibGit2Sharp/Core/NativeMethods.cs (hunk 25 above)
Comment (whoisj) [inline LibGit2Sharp/Core/NativeMethods.cs]: Yes - not sure why. I predates @ammeep changes.

**Comment by whoisj** [comment]
Updated the PR with a slight design change from what I started with. These changes are based on internal testing.

Basically, I removed the need for library consumers to supply meaningful return codes because there's no good way for them to know what meaningful code to return. Instead I've switch to an exceptional model where unless an exception is caught we assume `GitErrorCode.OK` and we translate exceptions into `GitErrorCode.Error`.

File: LibGit2Sharp/Filter.cs [hunk 34]
```diff
@@ -0,0 +1,396 @@
...
+        int InitializeCallback(IntPtr filterPointer)
+        {
+            int result = 0;
+            try
+            {
+                Initialize();
+            }
+            catch (Exception exception)
+            {
+                Trace.TraceError("Filter.InitializeCallback exception");
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: I wonder if we shouldn't rather use `Log` here (cf .https://github.com/libgit2/libgit2sharp/pull/832)

/cc @ethomson @jeffhostetler

File: LibGit2Sharp/Core/NativeMethods.cs (hunk 25 above)
Comment (ammeep) [inline LibGit2Sharp/Core/NativeMethods.cs]: The filter lifecycle is handled by libgit2 and it takes care of calling git_filter_free when we deregister.  I agree we should remove this.

File: LibGit2Sharp/Core/Proxy.cs [hunk 35]
```diff
@@ -816,7 +816,45 @@ public static int git_diff_num_deltas(DiffSafeHandle diff)
...
+
+        public static FilterMode git_filter_source_mode(IntPtr filterSource)
+        {
+            var res = NativeMethods.git_filter_source_mode(filterSource);
+            return (FilterMode)res;
+        }
+
+        public static void git_filter_free(IntPtr gitFilter)
+        {
+            NativeMethods.git_filter_free(gitFilter);
```
Comment (ammeep) [inline LibGit2Sharp/Core/Proxy.cs]: :fire: I think we can drop this ?

**Comment by ammeep** [comment]
Sorry for the delayed response - I have been on vacation :palm_tree: 

I have just ported our git-lfs filter in GitHub for Windows to use this and I have some feed back.

First up. What an **amazing job** you have done @whoisj :sparkles:  For small files it works perfectly, memory consumption looks stable as it streams small blobs through the filters API. :heart_eyes:  Thank you not only for for battling the interop gods, but preserving the consumer API. 

I tried streaming larger blobs - one of 1.5 and another of 3.5gb and saw an out of memory exception being raised from libgit2sharps error handler for both files. Is it worth adding integration tests for files this size?
 
```

   Out of memory

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Users\ammeep\Documents\GitHub\Windows\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in c:\Users\ammeep\Documents\GitHub\Windows\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_index_add_bypath(IndexSafeHandle index, FilePath path) in c:\Users\ammeep\Documents\GitHub\Windows\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 954
   at LibGit2Sharp.Repository.AddToIndex(String relativePath) in c:\Users\ammeep\Documents\GitHub\Windows\libgit2sharp\LibGit2Sharp\Repository.cs:line 1886
   at LibGit2Sharp.Repository.Stage(IEnumerable`1 paths, StageOptions stageOptions) in c:\Users\ammeep\Documents\GitHub\Windows\libgit2sharp\LibGit2Sharp\Repository.cs:line 1643
   at LibGit2Sharp.Repository.Stage(String path, StageOptions stageOptions) in c:\Users\ammeep\Documents\GitHub\Windows\libgit2sharp\LibGit2Sharp\Repository.cs:line 1591
   at LibGit2Sharp.RepositoryExtensions.Stage(IRepository repository, String path) in c:\Users\ammeep\Documents\GitHub\Windows\libgit2sharp\LibGit2Sharp\RepositoryExtensions.cs:line 622
   at GitHub.ExclusiveRepositoryConnection.<>c__DisplayClass3e.<StagePath>b__3d() in c:\Users\ammeep\Documents\GitHub\Windows\GitHub.Core\RepositoryConnections\ExclusiveRepositoryConnection.cs:line 554
   at System.Reactive.Linq.ObservableImpl.Defer`1.Eval()
   at System.Reactive.Helpers.Unpack[T](IObservable`1 source)
   at System.Reactive.TailRecursiveSink`1.MoveNext()
```

**Comment by whoisj** [comment]
@ammeep I did the same thing yesterday (HA!) and have been writing a fix. Should have it today. Trivial change, won't break the API. I'll get it up asap.

**Comment by whoisj** [comment]
I've updated the PR with changes that should fix the issue @ammeep is seeing with regards to OOM. I originally assumed the implementation class should be responsible for activity like this, but since it is a common scenario I've added the logic directly into the base class.

File: LibGit2Sharp/Core/Proxy.cs (hunk 35 above)
Comment (whoisj) [inline LibGit2Sharp/Core/Proxy.cs]: Yup - dropped in latest push

File: LibGit2Sharp/Core/NativeMethods.cs (hunk 25 above)
Comment (whoisj) [inline LibGit2Sharp/Core/NativeMethods.cs]: Removed.

**Comment by nulltoken** [comment]
@ammeep Could you please gave another test to this PR? :pray: 

@whoisj Amazing job! One thing that may be missing is a test leveraging a huge file. Maybe could we reuse @ethomson's (https://github.com/libgit2/libgit2/pull/2911) idea in the initial libgit2 PR and make the test only run on CI servers (à la `"/property:ExtraDefine="LEAKS_IDENTIFYING"`)

**Comment by ammeep** [comment]
@whoisj :cry: I'm still seeing out of memory exceptions when staging a file ```git_index_add_bypath(IndexSafeHandle index, FilePath path)```. The tricky thing is a bunch of interesting stuff happens here, I'm not sure if the filter pipeline is throwing, or if actual file staging that is.

**Comment by whoisj** [comment]
@ammeep are you using a 32-bit process? If so please see https://github.com/libgit2/libgit2/issues/3112

**Comment by carlosmn** [comment]
We use a particular function to set OOM, so if you can attach a debugger to stop when `giterr_set_oom()` gets called, that should let you know where that happens.

**Comment by whoisj** [comment]
@ammeep I closed the above mentioned issue as it should be an non-issue. The OOM situation is interesting. Is the error something like "File size overflow (for 32-bits) on 'test.blob': There are no more files."

**Comment by nulltoken** [comment]
@whoisj Did you intend to close *this* PR?

**Comment by whoisj** [comment]
@nulltoken  No I did not. The GH UX trips me up all the time :persevere:

**Comment by nulltoken** [comment]
:wink:

**Comment by whoisj** [comment]
@ameep I was able to contrive a local test which reproduces the OOM issue you reported (thank you :bow:) and have pushed a patch with a fix for it.

**Comment by ammeep** [comment]
GitHub for Windows is a 32bit process :cry: and there is one major block (unrelated to this project) which prevents us from shipping 64bit today (:soon: though) 

I've written a unit test which allowed me to test larger files outside of GitHub for Windows.  I don't see OOM exceptions here :sparkles: but I did get another new and interesting exception. 

Right now I am only testing the clean function (so what happens when a file is staged)

I got the following results out of the tests

```
| File Size 	| Time Taken 	| Result 	| Exeption                                                               	|
|-----------	|------------	|--------	|------------------------------------------------------------------------	|
| 1 MB      	| 1 Second   	| Pass   	|                                                                        	|
| 128 MB    	| 1 Minutes  	| Pass   	|                                                                        	|
| 256 MB    	| 3 Minutes  	| Pass   	|                                                                        	|
| 512 MB    	| 5 Minutes  	| Pass   	|                                                                        	|
| 1 GB      	| 7 Minutes  	| Fail   	| LibGit2Sharp.LibGit2SharpException: Filter write to next stream failed 	|
```

If you are wondering why it takes so long  - it's because we are generating large files,and reading from to assert expectations. I only included the times incase you ran the test - you might want to grab a cup of coffee :wink:

```
[Theory]
[InlineData(1L * 1024 * 1024)]     // 1 MB   takes about 1 second for test to run | Passes
[InlineData(128L * 1024 * 1024)]   // 128MB  ~ 1 minute | Passes
[InlineData(256L * 1024 * 1024)]   // 256MB  ~ 3 minutes | Passes
[InlineData(512L * 1024 * 1024)]   // 512MB  ~ 5 minutes | Passes
[InlineData(1024L * 1024 * 1024)]   // 1 GB  ~ 10 minutes |
public void CanCleanFilesOfVariousSizes(long seekToOffset)
{
    const char decodedInput = 't';
    const char encodedInput = 'g';

    string repoPath = InitNewRepository();

    var filter = new SubstitutionCipherFilter(FilterName + 18, attributes);
    var filterRegistration = GlobalSettings.RegisterFilter(filter);

    Assert.True(filter.CleanCalledCount == 0);
    Assert.DoesNotThrow(() =>
    {
        try
        {
            using (var repo = CreateTestRepository(repoPath))
            {
                var fileInfo = WriteSingleCharacterToEndOfLargeFile(repo, seekToOffset, decodedInput);
                repo.Stage(fileInfo.Name);
                var commit = repo.Commit("Initial commit");

                var blob = (Blob)commit.Tree[fileInfo.Name].Target;

                var blobStream = blob.GetContentStream();
                var lastCharacter = ReadSingleCharacterFromStream(blobStream, seekToOffset);
                Assert.Equal(encodedInput, lastCharacter);
            }
        }
        finally
        {
            GlobalSettings.DeregisterFilter(filterRegistration);
        }
    });
}

private FileInfo WriteSingleCharacterToEndOfLargeFile(IRepository repo, long seekToOffSet, char finalCharacter)
{
    string newFilePath = Path.Combine(repo.Info.WorkingDirectory, Guid.NewGuid() + ".txt");
    var fs = new FileStream(newFilePath, FileMode.CreateNew);
    fs.Seek(seekToOffSet, SeekOrigin.Begin);
    fs.WriteByte(Convert.ToByte(finalCharacter));
    fs.Close();
    return new FileInfo(newFilePath);
}

private char ReadSingleCharacterFromStream(Stream stream, long seekToOffSet)
{
    var lastByte = new byte[1];
    stream.Seek(seekToOffSet, SeekOrigin.Begin);
    stream.Read(lastByte, 0, 1);
    stream.Close();
    return Convert.ToChar(lastByte[0]);
}
```

There might be more efficient ways of doing this so feel free to take it and improve it. If you included it I think it would need some of what @nulltoken mentioned, wrapped around it though

>Maybe could we reuse @ethomson's (https://github.com/libgit2/libgit2/pull/2911) idea in the initial libgit2 PR and make the test only run on CI servers (à la `"/property:ExtraDefine="LEAKS_IDENTIFYING"`)

Also: I'll keep trying to get to the bottom of the OOM exceptions in GHfW.

**Comment by nulltoken** [comment]
@ammeep Amazing feedback :bangbang: :sparkling_heart:

**Comment by carlosmn** [comment]
That error message is set by `Filter.cs` which may be overwriting the original error message. It might provide more information to call `giterr_clear()` before the write (or the loop) and only set Filter's own error message if `giterr_last()` returns `NULL`.

I have mono 4 on my main machine, so I currently can't run tests, but maybe this helps someone who can.

**Comment by whoisj** [comment]
@ammeep can you retry your perf suite with the above changes. I believe you should find this a decided improvement on files > 4 MB. I'm seeing a 30-50x performance improvement on very large files (> 2GB).

**Comment by whoisj** [comment]
@nulltoken I've used Tasks (gasp!). Not seeing their use anywhere else in the library makes me concerned that I may have violated some written rule. Can you please review this change and give me your opinion? Thanks!

**Comment by whoisj** [comment]
The Travis failures are a bit cryptic. I'm seeing a lot of "The requested feature is not implemented" in the logs. Does this mean Mono doesn't support pipes? If not, is there an existing method to fork logic based on target? Is there a `#if MONO` preprocessor or similar?

**Comment by nulltoken** [comment]
>The Travis failures are a bit cryptic. I'm seeing a lot of "The requested feature is not implemented" in the logs. Does this mean Mono doesn't support pipes? If not, is there an existing method to fork logic based on target? Is there a `#if MONO` preprocessor or similar?

@Therzok @carlosmn Any hint, gentle :tophat: ?

**Comment by nulltoken** [comment]
@whoisj We moved to 4.0 in order to eventually (Maybe around v2.0) expose async ops. So, no we're not against using the `Task` type  *a priori* :wink:

I'll take a deep look at the changes tomorrow

**Comment by whoisj** [comment]
@nulltoken Thanks. I'm only using `Task`s to get cheap access to the threadpool. I can just as easily use a threadpool object if you prefer. At no place am I using `async`/`await`. :smirk:

**Comment by carlosmn** [comment]
I didn't remember that *Windows* supports them ;) The email you link to seems odd, since named pipes are specified by POSIX and both `mkfifo(1)` and `mkfifo(3)` have been around for a long time (unless that suddenly means something else).  And creating anonymous pipes via `pipe(2)` has been around for at least as long. But yeah, it looks like Mono hasn't implemented support for calling down to that.

This has me wondering however, why we need this file or two threads talking to each other. We don't need to keep the data around, so this seems like an unnecessary complication. From what I can see, we need this intermediate step because we call `WriteToNextFilter()` on a stream, and we want to perform the write as the user's filter performs the conversion and writes into the 'output' stream, as we otherwise need to keep the data around somewhere, which is either slow or can cause OOM.

If my understanding is correct, it seems like both saving to a file and using concurrency approach the problem from the wrong side. We have `nextStream` which we could make `Clean()` or `Smudge()` write directly to. If we want to still pass a `Stream` in order to keep the pure C# look, we can create our own Stream-derived class which translates its `Write()` method to the libgit2 one. If there's too many methods to make it reasonable, implementing `LibGit2Sharp.WriteStream` which implements a `Write()` and `Close()` or whatever it is we need and passing that to `Clean()` and `Smudge()` is IMO a much simpler way to solve the issue. Writing directly into the next stream is how the streaming filters were designed to work and this is how it's done inside libgit2.

File: LibGit2Sharp/Filter.cs [hunk 36]
```diff
@@ -0,0 +1,434 @@
...
+        internal GitFilter GitFilter
+        {
+            get { return gitFilter; }
+        }
+
+        /// <summary>
+        /// Complete callback on filter
+        /// 
+        /// This optional callback will be invoked when the upstream filter is
+        /// closed. Gives the filter a change to perform any final actions or
```
Comment (jamill) [inline LibGit2Sharp/Filter.cs]: change -> chance

**Comment by whoisj** [comment]
@carlosmn I'm about as far from a posix expert that there is. Unfortunately it does seem as if mono has omitted support for named pipes even if the underlying OS supports them.

The reason we're using pipes or a file system backed buffer is due to filters like LFS which random transform a tiny placeholder file in the odb into a many GB for in the worktree. The fetch from server can take minutes and exceed memory quickly.

Using named pipes was an attempt to avoid writing the file to disk twice. Looks like I'll need to implement another strategy or live with the reduced performance.

**Comment by carlosmn** [comment]
Right, for situations like LFS we don't want to keep everything in memory before passing it to the next stream. What I'm saying is that the writing to disk or using concurrency is due to the decisions inside `Filter` which we can avoid. We have an `Stream output` variable which the filter's `Clean()` and `Smudge()` write to, which is backed by an intermediate buffer, be it the file or pipe.

We can avoid this by making a write into `output` (or an equivalent) cause a write straight into `nextStream` instead of waiting for `WriteToNextFilter()` to execute.

We now have

    odb -> lg2s Filter -> [Stream output] -> WriteToNextStream -> nextStream.Write

and we could have something which looks more like

    odb -> lg2s Filter -> nextStream.Write

which wouldn't require any intermediate storage. In the case of LFS, that next stream would be the one which writes the final file. This would provide the same performance increase as using the pipes, though it would require either implementing a `Stream` which writes to `GitWriteStream` or exposing some type which wraps that.

**Comment by whoisj** [comment]
@carlosmn I do not disagree with your assessment. Asking filter writers to understand the lg2 flow and pipe reasonably sized chunks to the next filter would be ideal. Unfortunately, I don't believe the majority of developers will so well behaved. This isn't a knock on managed developers, but they tend to diregard memory consumption and when we're discussing a possibility of gigabytes of content being passed around things become fragile quickly; especially when you consider the memcpy across the managed/native barrier in addition to all other allocations.

What we had with the file backed stream:
```
odb -> lg2# Filter -> streamed buffer -> storage -> streamed buffer -> nextStream.Write
```
... and when chained ...
```
odb -> lg2# Filter -> streamed buffer -> storage -> streamed buffer -> nextStream.Write -> lg2# Filter -> streamed buffer -> storage -> streamed buffer -> nextStream.Write
```

What we had with the pipe based solution:
```
odb -> lg2# Filter -> pipe buffer -> nextStream.Write
```
... and when chained ...
```
odb -> lg2# Filter -> pipe buffer -> nextStream.Write -> lg2# Filter -> pipe buffer -> nextStream.Write
```

What we get with threaded pipe based solution:
```
odb -> lg2# Filter -> pipe buffer
                   -> nextStream.Write
```
... and when chained ...
```
odb -> lg2# Filter -> pipe buffer
                   -> nextStream.Write -> lg2# Filter -> pipe buffer 
                                                      -> nextStream.Write
```
Basically mitigating the latency caused by slow filters by attempting to hide the latency by streaming bytes to the next filter as the current filter is still working. Without threading, this isn't really possible unless the filter itself implements the threading - and most won't: they'll use the local primary thread to process bytes.

So the benefit of putting the piping and parallellization logic into the library is:
* Safe concurrency of filters
* Management of memory consumption
* Simple API that is easy to adapt to existing Git filters

**Comment by carlosmn** [comment]
I don't see how adding threads helps with someone writing out a large file on their main thread, seeing how we call `WriteToNextStream()` on that thread and wait for the I/O to finish anyway. These filters are run either via adding files to the index or performing a checkout. These are already very large operations to run on the main thread even before we get filters involved.

The way the libgit2 filter is set up is very similar to how you'd use a writer into a file stream. What you write gets put on the filesystem, and the concurrency is provided by the operating system or underlying platform via its normal I/O mechanisms, and this is what libgit2 filters provide, we don't need to add anything, we just need to make the filter's writes become I/O on disk as soon as possible; and this should also make straightforward code be performant by not buffering anything ourselves. Say that you have a smudge filter for LFS, and you have some `Stream` from a method which reads from S3 or VSO or whatever is doing the file hosting via HTTP. You'd want to read from it and write directly to the output. This would be something like

```C#
void Smudge(string path, string root, Stream input, Stream output)
{
    var networkStream = getNetworkStreamForLFS(input);
    networkStream.CopyTo(output);
}
```

where `getNetworkStreamForLFS()` reads and parses the LFS format from the odb, figures out which URL you want to download the file from and returns a network stream to that file. If you were writing this in isolation, you'd just `CopyTo()` into a `FileStream()` you just created. Here, you have to give the output to libgit2(sharp) instead, but by creating a `Stream`-derived class which just proxies each to the next stream, we create the same behaviour as the "normal" stream to a file. In the normal case, which is a single smudge filter, the next stream just does a `write()` to the filesystem anyhow. In case we do have a next filter implemented in libgit2sharp, using threading isn't going to help more than simply giving them the writes directly.

If the filters are inefficient, that's not something we can fix via the threading, as we're just doing a two-step process for passing the data along.

I have implemented a PoC in https://github.com/carlosmn/libgit2sharp/commits/streaming-filter-support which implements what I've been suggesting. It does away with any form of buffering or threading and just passes the data along. Due to the whole mono-4/xunit thing, I can't actually run the tests, but it should provide a decent base, as it probably needs some `null` checks and whatnot. I'd expect the peformance to be at least as good as with the threaded variant.

**Comment by whoisj** [comment]
@carlosmn love the simplicity. It really is quite elegant.

My initial rebuttal was that the only issue I'm seeing with it, is that it doesn't force filter writers to do the "right thing(tm)". If you look at the test code provided, for example (not trying to pick on anyone), the filter writes a single byte to the next filter each time.

```
        public static void RotateByThirteenPlaces(Stream input, Stream output)
        {
            int value;

            while ((value = input.ReadByte()) != -1)
            {
                if ((value >= 'a' && value <= 'm') || (value >= 'A' && value <= 'M'))
                {
                    value += 13;
                }
                else if ((value >= 'n' && value <= 'z') || (value >= 'N' && value <= 'Z'))
                {
                    value -= 13;
                }

                output.WriteByte((byte)value);
            }
        }
```

My assumption was the cost of marshaling would be significant, however after doing a series of bench marks against the above filter (worst case) and a 1GB file I found the times to be fairly comparable. My complex (custom pipes) were only a couple of seconds faster on average. A nearly non-noticeable difference given the significant added complexity they introduce.

So THANK YOU, I'll update my PR by including your commit. It requires some touch up, so I'll get on those then push the update.

@nulltoken @ethomson I've a large file test now. There was some discussion about how to add those so that they only run when asked for. How has this been setup in the past? I'd like to leverage whatever work has been done in this space. Thanks!

**Comment by whoisj** [comment]
I had a post with performance numbers, but I just realized that all data was incorrect. I've removed that post and am re-running all tests to acquire new numbers.

**Comment by whoisj** [comment]
@carlosmn I completely agree that your model is a lot simpler, however there are severe issues with performance of large files with sub-optimal filters. Take the `RotateByThirteenPlaces` test filter used to verify Filter.cs. It does the worst possible way of passing data down to lg2: byte by byte. This incurs a heavy cost as each individual byte gets marshaled across the managed/native barrier.
```
        public static void RotateByThirteenPlaces(Stream input, Stream output)
        {
            int value;

            while ((value = input.ReadByte()) != -1)
            {
                if ((value >= 'a' && value <= 'm') || (value >= 'A' && value <= 'M'))
                {
                    value += 13;
                }
                else if ((value >= 'n' && value <= 'z') || (value >= 'N' && value <= 'Z'))
                {
                    value -= 13;
                }

                output.WriteByte((byte)value);
            }
        }
```

As it turns out, it's an ideal tests for validating the performance strategies used in our filter infrastructure.

In my opinion, libraries should make code development easy; even for bad developers. If we can hold a developer's hand, why not do so?

Sample results using the inline streaming design:
```
CanFilterLargeFiles                                               | 3 min
CanRegisterFilterWithSingleAttribute                              | 3 ms
CleanFilterWritesOutputToObjectTree                               | 133 ms
InitCallbackMadeWhenUsingTheFilter                                | 120 ms
WhenCheckingOutAFileFileSmudgeWritesCorrectFileToWorkingDirectory | 266 ms
WhenStagingFileApplyIsCalledWithCleanForCorrectPath               | 52 ms
```

The entire point of all the work I did with buffers and threading was to mitigate the cost of marshaling from managed to native by limiting it to as few buffers as possible. 

Sample results using the threaded streaming design:
```
CanFilterLargeFiles                                               | 58 sec
CanRegisterFilterWithSingleAttribute                              | 43 ms
CleanFilterWritesOutputToObjectTree                               | 35 ms
InitCallbackMadeWhenUsingTheFilter                                | 15 ms
WhenCheckingOutAFileFileSmudgeWritesCorrectFileToWorkingDirectory | 46 ms
WhenStagingFileApplyIsCalledWithCleanForCorrectPath               | 137 ms
```

As you can see there's a huge discrepancy in the large file filtering performance, enough so that I feel that it's not just micro-benchmark noise coming into play. However, the small files suffered when filtered due to the cost of queuing thread work and joining the results. Additionally, I simply preferred your simpler approach.

So I started thinking about how to keep the simplicity while keeping the number of marshaling calls to an absolute minimum.

Results to doing it right:
```
CanFilterLargeFiles                                               | 4 sec
CanRegisterFilterWithSingleAttribute                              | 1 ms
CleanFilterWritesOutputToObjectTree                               | 51 ms
InitCallbackMadeWhenUsingTheFilter                                | 17 ms
WhenCheckingOutAFileFileSmudgeWritesCorrectFileToWorkingDirectory | 44 ms
WhenStagingFileApplyIsCalledWithCleanForCorrectPath               | 14 ms
```

In fact the difference was so staggering, I've spent the last two hours confirming the data. Still not believing it - it has to be my tired mind playing tricks on me.

**Comment by carlosmn** [comment]
The rot13 filter is an extreme example of how not to write performant stream processing code. It's not surprising that it takes thrice as long as the multithreaded variant, and I don't feel particularly bad if that code is slow (though if we can easily make it fast, then that's obviously good). I was not thinking of this kind of code when writing my implementation, but rather the output explosion we get from LFS which would provide abundant content for the output stream.

The pipe and file methods build buffering into the system, and if we're benchmarking the worst-case scenario here, it's not surprising that multi-threaded version wins out even though it requires a lot more coordination, as the cost of calling down to libgit2 would dominate in the inline version.

Evidently the `BufferedStream` (assuming that's what you mean by "doing it right") is able to cut down these calls to libgit2 considerably, writing down in blocks of 64k, eliminating the first 64k-1 writes to the output stream, which brings us back to the the first paragraph. Though the inline + caching does cut down on the number of allocations and copies (we avoid the whole `memcpy`ing from `WriteToNextStream` and the copying to and fro the intermediate buffer between threads), the difference in speed is impressive. This must be why every layer of IO in the OS has some caching in it.

**Comment by whoisj** [comment]
Yes "doing it right" meant your method plus buffering to reduce calls into the native layer. Fewer, larger is better performing than frequent, small calls.

Regardless, we mostly have a solution now. Just need to resolve

* Getting there large file test working
* Deciding if we throw in error or not (I vote not)

**Comment by whoisj** [comment]
OK large file test added and working. Looks like we're green on the tests.

Still wondering how to make tests optional or if we should even bother.

Anything else?

**Comment by nulltoken** [comment]
> Still wondering how to make tests optional or if we should even bother.

Why don't you apply the same trick we use for identifying leaks while running tests on the CI servers (cf https://github.com/libgit2/libgit2sharp/pull/883)?

**Comment by carlosmn** [comment]
The issue with that approach is that you don't compile the tests. I like the approach in libgit2 which compiles everything but will skip a test if an env variable isn't set. Is there some way to skip a test from inside in xunit? Or can you tag certain tests to not run by default?

**Comment by nulltoken** [comment]
>The issue with that approach is that you don't compile the tests. 

@carlosmn How so? The symbol will be defined when ran on the CI server. As such the test will be compiled, won't it?

**Comment by carlosmn** [comment]
The CI would complain, but it would only be compiled through the CI job, no? If someone changes a type, or ranames something, or anything else that wold cause a compilation error there, they wouldn't notice it until the CI tells them, which is a fairly long feedback cycle.

We may not want to run the tests by default outside the CI, but there's still value in making sure the tests compile before sending a pull request.

**Comment by shiftkey** [comment]
@ammeep can you have a look at the recent changes here and see if you're happy with this?

@whoisj there's been some changes here which mean this PR no longer merges. Could you merge `vNext` into this branch to get it up to date?

**Comment by nulltoken** [comment]
> @whoisj there's been some changes here which mean this PR no longer merges. Could you merge vNext into this branch to get it up to date?

Or rather rebase this branch on top of vNext.

**Comment by whoisj** [comment]
@shiftkey yes, I'll sort out the merge issue.

@nulltoken, I assume `rebase` was preferred (it is, at least by me) and I'm working through the long list of conflicts.

**Comment by whoisj** [comment]
@nulltoken, @shiftkey `rebase` completed, merge looks clean, tests passing.

Enjoy!

**Comment by ammeep** [comment]
:sparkling_heart: Taken this for a spin and it is looking fantastic - a huge improvement!

File: LibGit2Sharp.Tests/FilterFixture.cs [hunk 37]
```diff
@@ -0,0 +1,387 @@
...
+
+            contentFile.Delete();
+
+            GlobalSettings.DeregisterFilter(filterRegistration);
+        }
+
+        private unsafe bool CharArrayAreEqual(char[] array1, char[] array2, int count)
+        {
+            if (Object.ReferenceEquals(array1, array2))
+                return true;
```
Comment (nulltoken) [inline LibGit2Sharp.Tests/FilterFixture.cs]: Style nitpick: Could you please braces here and below?

File: LibGit2Sharp.Tests/FilterFixture.cs [hunk 38]
```diff
@@ -0,0 +1,387 @@
...
+
+            fixed (char* c1 = array1, c2 = array2)
+            {
+                long* p1 = (long*)c1,
+                      p2 = (long*)c2;
+
+                for (int i = 0; i < cnt; i++)
+                {
+                    if (p1[i] != p2[i])
+                        return false;
```
Comment (nulltoken) [inline LibGit2Sharp.Tests/FilterFixture.cs]: Here as well

File: LibGit2Sharp.Tests/FilterFixture.cs [hunk 39]
```diff
@@ -0,0 +1,387 @@
...
+                }
+
+                byte* b1 = (byte*)c1,
+                      b2 = (byte*)c2;
+
+                for (int i = len * sizeof(long); i < len; i++)
+                {
+                    if (b1[i] != b2[i])
+                        return false;
```
Comment (nulltoken) [inline LibGit2Sharp.Tests/FilterFixture.cs]: Here as well

File: LibGit2Sharp/Core/Proxy.cs [hunk 40]
```diff
@@ -801,7 +801,34 @@ public static int git_diff_num_deltas(DiffSafeHandle diff)
...
+            return NativeMethods.git_diff_get_delta(diff, (UIntPtr)idx).MarshalAs<GitDiffDelta>(false);
+        }
+
+        #endregion
+
+        #region git_filter_
+
+        public static void git_filter_register(string name, FilterRegistration filterRegistration, int priority)
+        {
+                int res = NativeMethods.git_filter_register(name, filterRegistration.FilterPointer, priority);
```
Comment (nulltoken) [inline LibGit2Sharp/Core/Proxy.cs]: Indentation looks a bit off in this method and the one below

File: LibGit2Sharp/Filter.cs [hunk 41]
```diff
@@ -0,0 +1,342 @@
...
+        /// 
+        /// This optional callback will be invoked when the upstream filter is
+        /// closed. Gives the filter a chance to perform any final actions or
+        /// necissary clean up.
+        /// </summary>
+        /// <param name="path">The path of the file being filtered</param>
+        /// <param name="root">The path of the working directory for the owning repository</param>
+        /// <param name="output">Output to the downstream filter or output writer</param>
+        protected virtual void Complete(string path, string root, Stream output)
+        {
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: Could you put the closing brace on the same line than the opening one, please?

File: LibGit2Sharp/Filter.cs [hunk 42]
```diff
@@ -0,0 +1,342 @@
...
+        /// Specified as `filter.initialize`, this is an optional callback invoked
+        /// before a filter is first used.  It will be called once at most.
+        ///
+        /// If non-NULL, the filter's `initialize` callback will be invoked right
+        /// before the first use of the filter, so you can defer expensive
+        /// initialization operations (in case the library is being used in a way
+        /// that doesn't need the filter.
+        /// </summary>
+        protected virtual void Initialize()
+        {
```
Comment (nulltoken) [inline LibGit2Sharp/Filter.cs]: Here as well

**Comment by nulltoken** [comment]
@whoisj :+1: 

Once the last nitpicks are nailed, could you please simplify the history by squashing the fixup commits?

**Comment by nulltoken** [comment]
> Still wondering how to make tests optional or if we should even bother.

@whoisj Forgot about this. How long does this test actually take to run?

**Comment by whoisj** [comment]
> Once the last nitpicks are nailed, could you please simplify the history by squashing the fixup commits?

@nulltoken nit cleaned up. History squashed to make me look good while keeping attribution for @ammeep and @carlosmn correct.

> @whoisj Forgot about this. How long does this test actually take to run?

The "big file" test takes about 3 seconds on my lowly Surface Pro 3. I'm hoping the servers Travis and AppVeyor use are faster. I really do not think it should be a major issue. :smirk:

**Comment by nulltoken** [comment]
Dammit! The PR isn't mergeable any longer. Could you please rebase it?

**Comment by whoisj** [comment]
@nulltoken oh that was a fun merge (in the text sense) :expressionless:

**Comment by nulltoken** [comment]
@whoisj @ammeep 

love

**Comment by whoisj** [comment]
:tada: :balloon: :beers: :relieved:

**Comment by dahlbyk** [comment]
Epic.

**Comment by ammeep** [comment]
:tada: Nice work @whoisj!!

**Comment by shiftkey** [comment]
Nice work @ammeep and @whoisj!

**Comment by whoisj** [comment]
Thanks to @ethomson for the base work in Libgit2, @ammeep for the base work in this library, and to @carlosmn for being awesome and putting my head on straight there at the end. :bow:

**Comment by nulltoken** [comment]
@whoisj This **[AppVeyor job](https://ci.appveyor.com/project/libgit2/libgit2sharp/build/job/a1iorcsr2lv1bf4j)** shows some strange failures related this PR. Any idea?

```
LibGit2Sharp.Tests.FilterFixture.CanFilterLargeFiles [FAIL]
   System.NullReferenceException : Object reference not set to an instance of an object.
 
LibGit2Sharp.Tests.FilterFixture.WhenStagingFileApplyIsCalledWithCleanForCorrectPath [FAIL]
   System.NullReferenceException : Object reference not set to an instance of an object.
 
LibGit2Sharp.Tests.FilterFixture.CleanFilterWritesOutputToObjectTree [FAIL]
   System.NullReferenceException : Object reference not set to an instance of an object.
 
LibGit2Sharp.Tests.FilterFixture.WhenCheckingOutAFileFileSmudgeWritesCorrectFileToWorkingDirectory [FAIL]
   System.NullReferenceException : Object reference not set to an instance of an object.
```

**Comment by nulltoken** [comment]
Some more detail in this **[other one](https://ci.appveyor.com/project/libgit2/libgit2sharp/build/934/job/v23w8kafl9ybmqkf)**

```
LibGit2Sharp.Tests.FilterFixture.CanFilterLargeFiles [FAIL]
   System.NullReferenceException : Object reference not set to an instance of an object.
 
LibGit2Sharp.Tests.FilterFixture.CleanFilterWritesOutputToObjectTree [FAIL]
   System.NullReferenceException : Object reference not set to an instance of an object.
 
LibGit2Sharp.Tests.FilterFixture.WhenCheckingOutAFileFileSmudgeWritesCorrectFileToWorkingDirectory [FAIL]
   LibGit2Sharp.LibGit2SharpException : Unexpected IntPtr value
   Parameter name: stream
   Stack Trace:
      c:\projects\libgit2sharp\LibGit2Sharp\Core\Ensure.cs(154,0): at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
      c:\projects\libgit2sharp\LibGit2Sharp\Repository.cs(1722,0): at LibGit2Sharp.Repository.Stage(IEnumerable`1 paths, StageOptions stageOptions)
      c:\projects\libgit2sharp\LibGit2Sharp.Tests\FilterFixture.cs(319,0): at LibGit2Sharp.Tests.FilterFixture.StageNewFile(IRepository repo, String contents)
      c:\projects\libgit2sharp\LibGit2Sharp.Tests\FilterFixture.cs(293,0): at LibGit2Sharp.Tests.FilterFixture.CheckoutFileForSmudge(String repoPath, String branchName, String content)
      c:\projects\libgit2sharp\LibGit2Sharp.Tests\FilterFixture.cs(170,0): at LibGit2Sharp.Tests.FilterFixture.WhenCheckingOutAFileFileSmudgeWritesCorrectFileToWorkingDirectory()
 
LibGit2Sharp.Tests.FilterFixture.WhenStagingFileApplyIsCalledWithCleanForCorrectPath [FAIL]
   System.NullReferenceException : Object reference not set to an instance of an object.
```

**Comment by whoisj** [comment]
@nulltoken it's very possible something went wrong in the series of rebases the PR took just before merge. I'm not able to reproduce these failures locally. Do they only happen in AppVeyor or can you reproduce them locally?

**Comment by nulltoken** [comment]
>I'm not able to reproduce these failures locally.

I'm not either.

Weirder, see https://ci.appveyor.com/project/libgit2/libgit2sharp/history

 - Build 934 fails -> https://github.com/libgit2/libgit2sharp/pull/859
 - Build 935 passes -> https://github.com/libgit2/libgit2sharp/pull/1062
 - Build 936 fails -> https://github.com/libgit2/libgit2sharp/pull/859

Just restarted #859 build to see if this is consistent (although I'm not sure to understand why). May AppVeyor prefers @ethomson's code over @jamill's code

**Comment by nulltoken** [comment]
*Very* strange. https://github.com/libgit2/libgit2sharp/pull/859 is now passing.

This kind of random issues makes me feel *very* uneasy especially when the tests do not rely on external dependencies (eg. network).

**Comment by whoisj** [comment]
@nulltoken I see trancient test failures commonly in the `BlobFixture`, the `FilterFixture`, the `ArchiveFixture`, and the `CheckoutFixture` several times a day and a re-run of the tests nearly always resolves the issue. The errors are always the same: either `NullReferenceException` or `DirectoryNotFound` exceptions - at least for me.

This has been happening since before I started on the project and since they were always transient and always resolved by a re-run I ignored them.

**Comment by nulltoken** [comment]
@whoisj Wow. That is *very* weird. I've never seen `BlobFixture/ArchiveFixture/CheckoutFixture` failing. Neither locally, nor in the CI logs.

With regards to your failures, are you still running the tests against a RAM disk? Could we be experiencing IO concurrency issues?

**Comment by whoisj** [comment]
@nulltoken I am using the RAM disk locally, but the transient failures have been happening since before I switched from SSD to RAM. I do not think they're related. One piece of information I do have is it feels like it's more common to see transient failures immediately after building. In fact, I do not believe I've ever seen them when using an existing DLL. JIT issues?

**Comment by nulltoken** [comment]
Regarding https://github.com/libgit2/libgit2sharp/pull/1030#issuecomment-111146995 @jeffhostetler was hinting at a possible GC related reclaim.

**Comment by whoisj** [comment]
The failure line for one of the tests is consistently `char[] content = (new string(ContentValue, 1024)).ToCharArray();` which makes me think the GC is collection the `new string(...)` before the `.ToCharArray()` is called, resulting in a NRE.

**Comment by dahlbyk** [comment]
CI `FilterFixture` failure: https://ci.appveyor.com/project/libgit2/libgit2sharp/build/995/job/qse6k53u5v040045#L205

**Comment by carlosmn** [comment]
One of those errors are from writing to the next stream, which sets its own error message. It should provide more information about the underlying cause if `WriteStream.Write()` were to use `Ensure.ZeroResult()` as it could simply be that we're running out of disk space, but in any case it should tell us why libgit2 returned an error.
